"use client";
import Head from "next/head";

const Header = () => {
  return (
    <>
      <Head>
        <title>Marius portfolio</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="Portfolio" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};
export default Header;
