'use client';
import Head from 'next/head';

const Header = () => {
  return (
    <>
      <title>Marius portfolio</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="Portfolio" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
};
export default Header;
